services:
  spotify-rpm:
    container_name: spotify-rpm
    image: spotify-rpm
    build:
      dockerfile: dockerfile-el8
      #dockerfile: dockerfile-el9
      #dockerfile: dockerfile-el10
      #dockerfile: dockerfile-fc-previous
      #dockerfile: dockerfile
      #dockerfile: dockerfile-fc-beta
      #dockerfile: dockerfile-fc-rawhide
      #dockerfile: dockerfile-leap-previous
      #dockerfile: dockerfile-leap
      #dockerfile: dockerfile-tumbleweed
    environment:
      - INTERVAL=1d
    volumes:
      - ./data:/data