services:
  spotify-rpm-packager:
    container_name: spotify-rpm-packager
    image: spotify-rpm-packager:latest
    build: .
    env_file: .env
    privileged: True
    ports:
      - ${PORT:-80}:${PORT:-80}
    volumes:
      - ./data:/data
      - ./gpg:/gpg-key