services:
  spotify-rpm:
    container_name: rpm-spotify-package-generator
    image: rpm-spotify-package-generator
    build:
      #dockerfile: dockerfile-el8
      #dockerfile: dockerfile-el9
      #dockerfile: dockerfile-el10
      #dockerfile: dockerfile-fc-previous
      dockerfile: dockerfile
      #dockerfile: dockerfile-fc-beta
      #dockerfile: dockerfile-fc-rawhide
    environment:
      - INTERVAL=5m
      - DISABLE_WEB_SERVER=0
      - GPG_NAME=Zic Stardust
      - GPG_EMAIL=me@zicstardust.com
    ports:
      - 80:80
    volumes:
      - ./data:/data
      - ./gpg:/gpg-key