services:
  spotify-rpm:
    container_name: rpm-spotify-package-generator
    image: rpm-spotify-package-generator:latest
    build: .
    env_file: .env
    privileged: True
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
      - ./gpg:/gpg-key