name: Push images to docker hub

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  PLATAFORM_ARCH: linux/amd64
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
  FEDORA_PREVIOUS: 42
  FEDORA_CURRENT: 43
  FEDORA_BETA: 44
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                
      -
        name: Build and push - fc${{ vars.FEDORA_CURRENT }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:fc${{ vars.FEDORA_CURRENT }}
            ${{ env.CONTAINER_REPO }}:latest

      -
        name: Build and push - fc${{ vars.FEDORA_PREVIOUS }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fedora-previous
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:fc${{ vars.FEDORA_PREVIOUS }}

      -
        name: Build and push - fc${{ vars.FEDORA_BETA }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fedora-beta
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:fc${{ vars.FEDORA_BETA }}

      -
        name: Build and push - rawhide
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fedora-rawhide
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:rawhide

      -
        name: Build and push - Enterprise Linux 8
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el8
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el8

      -
        name: Build and push - Enterprise Linux 9
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el9
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el9

      -
        name: Build and push - Enterprise Linux 10
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el10
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el10