name: Push images to docker hub

on:
  push:
    branches: [ "main" ]
    paths:
      - scripts/**
      - dockerfile**
      - entrypoint.sh

  pull_request:
    branches: [ "main" ]
    paths:
      - scripts/**
      - dockerfile**
      - entrypoint.sh

env:
  PLATAFORM_ARCH: linux/amd64
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
  FEDORA_PREVIOUS: 42
  FEDORA_CURRENT: 43
  FEDORA_BETA: 44
  LEAP_PREVIOUS: 15
  LEAP_CURRENT: 16
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                
      -
        name: Build and push - fc${{ env.FEDORA_CURRENT }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:fc${{ env.FEDORA_CURRENT }}
            ${{ env.CONTAINER_REPO }}:latest

      -
        name: Build and push - fc${{ env.FEDORA_PREVIOUS }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fc-previous
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
              ${{ env.CONTAINER_REPO }}:fc-previous
              ${{ env.CONTAINER_REPO }}:fc${{ env.FEDORA_PREVIOUS }}

      -
        name: Build and push - fc${{ env.FEDORA_BETA }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fc-beta
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
              ${{ env.CONTAINER_REPO }}:fc${{ env.FEDORA_BETA }}
              ${{ env.CONTAINER_REPO }}:fc-beta

      -
        name: Build and push - rawhide
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fc-rawhide
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:rawhide

      -
        name: Build and push - Enterprise Linux 8
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el8
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el8

      -
        name: Build and push - Enterprise Linux 9
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el9
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el9

      -
        name: Build and push - Enterprise Linux 10
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el10
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:el
            ${{ env.CONTAINER_REPO }}:el10
          

      -
        name: Build and push - openSUSE Leap ${{ env.LEAP_PREVIOUS }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-leap-previous
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
              ${{ env.CONTAINER_REPO }}:leap${{ env.LEAP_PREVIOUS }}
              ${{ env.CONTAINER_REPO }}:leap-previous


      -
        name: Build and push - openSUSE Leap ${{ env.LEAP_CURRENT }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-leap
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:leap${{ env.LEAP_CURRENT }}
            ${{ env.CONTAINER_REPO }}:leap


      -
        name: Build and push - openSUSE Tumbleweed
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-tumbleweed
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:tumbleweed