name: Push images Fedora to ghcr.io

on:
  push:
    branches: [ "main" ]
    paths:
      - scripts/**
      - dockerfile
      - dockerfile-fc**
      - entrypoint.sh
      - .github/workflows/push-fc-images-to-ghrc.yml

  pull_request:
    branches: [ "main" ]
    paths:
      - scripts/**
      - dockerfile
      - dockerfile-fc**
      - entrypoint.sh
      - .github/workflows/push-fc-images-to-ghrc.yml

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  PLATAFORM_ARCH: linux/amd64
  CONTAINER_REPO: ghcr.io/${{ GITHUB.REPOSITORY }}
  FEDORA_PREVIOUS: 42
  FEDORA_CURRENT: 43
  FEDORA_BETA: 44
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ GITHUB.REPOSITORY_OWNER }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
          #driver-opts: image=moby/buildkit:master
                
      - name: Build and push - fc${{ env.FEDORA_CURRENT }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:fc${{ env.FEDORA_CURRENT }}
            ${{ env.CONTAINER_REPO }}:latest

      - name: Build and push - fc${{ env.FEDORA_PREVIOUS }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fc-previous
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
              ${{ env.CONTAINER_REPO }}:fc-previous
              ${{ env.CONTAINER_REPO }}:fc${{ env.FEDORA_PREVIOUS }}

      - name: Build and push - fc${{ env.FEDORA_BETA }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fc-beta
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
              ${{ env.CONTAINER_REPO }}:fc${{ env.FEDORA_BETA }}
              ${{ env.CONTAINER_REPO }}:fc-beta

      - name: Build and push - rawhide
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-fc-rawhide
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:rawhide
