name: Push images Enterprise Linux to docker hub

on:
  push:
    branches: [ "main" ]
    paths:
      - scripts/**
      - dockerfile-el**
      - entrypoint.sh
      - .github/workflows/push-el-images-to-dockerhub.yml

  pull_request:
    branches: [ "main" ]
    paths:
      - scripts/**
      - dockerfile-el**
      - entrypoint.sh
      - .github/workflows/push-el-images-to-dockerhub.yml

env:
  PLATAFORM_ARCH: linux/amd64
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                

      - name: Build and push - Enterprise Linux 8
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el8
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el8

      - name: Build and push - Enterprise Linux 9
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el9
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:el9

      - name: Build and push - Enterprise Linux 10
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile-el10
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:el
            ${{ env.CONTAINER_REPO }}:el10
          